### ISSUE TITLE
Reduce Dependabot spam

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/archetypes#288]
The average low activity plugin gets way too much Dependabot spam via this default configuration. See e.g. https://github.com/jenkinsci/solarized-theme-plugin/pulls?q=is%3Apr

The frequency of at least parent POM and BOM updates needs to be dialed waaaayyy back by default.

Per https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#scheduleinterval it looks like the lowest possible value is `monthly` which still seems like a lot.

Excluding these dependencies is probably not OK either though.

Do we need a custom GH action for Jenkins dependencies to handle this, instead of Dependabot? 😦

**Comment by timja** [comment]
Personally what I do is on a Monday morning when all the PRs come in is:

Click 'Open all in new tabs'
Go through every tab approving and copy pasting `@dependabot merge`
Takes a couple of minutes
and I don't normally bother evaluating any that have failed

The other alternative I guess is to disable it in the repo you're using?

**Comment by daniel-beck** [comment]
This doesn't reasonably scale tp many plugins that don't change a lot.

It's fine for a component that gets fixed and is regularly released anyway, but I'd be at probably a dozen releases of `solarized-theme` in 6 months now, with nothing of any interest having changed about the plugin. Or PRs merged on top of unreleased PRs, all updating the same dependency. Who does this help in any way?

**Comment by jglick** [comment]
I am fine with https://github.com/jenkinsci/archetypes/blob/4000310da3eacb6bafc889d4e032ff2c98a8a2fe/common-files/.github/dependabot.yml#L8 being changed to `monthly`. https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval does not offer anything slower than that.

**Comment by timja** [comment]
Could also just add a comment with options and let the maintainer choose?

**Comment by jglick** [comment]
Well if you _find_ this file it should be obvious what to change. The question is about which default would be appropriate for a typical plugin maintainer.
