### ISSUE TITLE
ArchetypeCatalog is not supported anymore

### ISSUE THREAD

**Issue by mehulparmariitr** [jenkinsci/archetypes#502]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

macos

### Reproduction steps

mvn archetype:generate -Dfilter=io.jenkins.archetypes:

### Expected Results

generate any sample plugin unit test

### Actual Results

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project archetypes-parent: archetypeCatalog 'abc.xml' is not supported anymore. Please read the plugin documentation for details. -> [Help 1]

### Anything else?

If there is any other way to generate hello world plugin unit test samples, please provide that link/git repo.

**Comment by daniel-beck** [comment]
Works for me, even without custom Maven `settings.xml` or pre-filled `.m2/repository`, with Maven 3.8.6.

Please make sure you don't have weird custom settings (what is `abc.xml`?), an outdated version of Maven, or similar.
