### ISSUE TITLE
verify hello world plugin error

### ISSUE THREAD

**Issue by markixy** [jenkinsci/archetypes#684]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

window10 
maven3.4.0

### Reproduction steps

1. mvn archetype:generate -B -DarchetypeGroupId=io.jenkins.archetypes -DarchetypeArtifactId=empty-plugin -DhostOnJenkinsGitHub=true -DarchetypeVersion=1.20 -DartifactId=somefeature
2. cd somefeature
3. mvn verify

### Expected Results

success

### Actual Results

[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.jenkins.plugins:somefeature:1.0-SNAPSHOT (E:\jenkins-my-plug\somefeature\pom.xml) has 2 errors
[ERROR]     Malformed POM E:\jenkins-my-plug\somefeature\pom.xml: Unknown attribute 'child.scm.url.inherit.append.path' for tag 'scm' (position: START_TAG seen ...rit.append.path="false" child.scm.url.inherit.append.path="false">... @22:157)  @ E:\jenkins-my-plug\somefeature\pom.xml, line 22, column 157 -> [Help 2]
[ERROR]     Unknown packaging: hpi @ io.jenkins.plugins:somefeature1:${revision}${changelist}, E:\jenkins-my-plug\somefeature\pom.xml, line 13, column 14
[ERROR]

**Comment by markixy** [comment]
I tried to comment it out. 
```xml
<!-- <packaging>hpi</packaging>-->
...
<!-- <scm child.scm.connection.inherit.append.path="false" child.scm.developerConnection.inherit.append.path="false" child.scm.url.inherit.append.path="false">
...
  </scm> -->
```
and then execute `mvn verify` agent, get other error.

[INFO] ------------------------------------------------------------------------
Downloading: https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.387.3/jenkins-war-2.387.3.executable-war
Downloading: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.387.3/jenkins-war-2.387.3.executable-war
...
[ERROR] Failed to execute goal on project somefeature: Could not resolve dependencies for project io.jenkins.plugins:somefeature:jar:1.0-SNAPSHOT: Could not find artifact org.jenkins-ci.main:jenkins-war:executable-war:2.387.3 in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) -> [Help 1]
[ERROR]

it realy not exists.
![image](https://github.com/jenkinsci/archetypes/assets/83167421/12709d91-48d3-4202-a2b2-e338cfa689c4)

**Comment by jonesbusy** [comment]
I don't see any maven 3.4.0 here: https://maven.apache.org/docs/history.html

But if you are still on 3.0.4 you need to update it. It's end of life.

Also I cannot reproduce using same commands.

Also more recent archetype is available (1.22)

```
mvn archetype:generate -B -DarchetypeGroupId=io.jenkins.archetypes -DarchetypeArtifactId=empty-plugin -DhostOnJenkinsGitHub=true -DarchetypeVersion=1.22 -DartifactId=somefeature
```

**Comment by NotMyFault** [comment]
> I don't see any maven 3.4.0 here: [maven.apache.org/docs/history.html](https://maven.apache.org/docs/history.html)
> 
> But if you are still on 3.0.4 you need to update it. It's end of life.
> 
> Also I cannot reproduce using same commands.
> 
> Also more recent archetype is available (1.22)
> 
> ```
> mvn archetype:generate -B -DarchetypeGroupId=io.jenkins.archetypes -DarchetypeArtifactId=empty-plugin -DhostOnJenkinsGitHub=true -DarchetypeVersion=1.22 -DartifactId=somefeature
> ```

I can't reproduce that either using maven 3.9.6, but the war does definitely exist in artifactory under that URL.

**Comment by markixy** [comment]
> I don't see any maven 3.4.0 here: https://maven.apache.org/docs/history.html
> 
> But if you are still on 3.0.4 you need to update it. It's end of life.
> 
> Also I cannot reproduce using same commands.
> 
> Also more recent archetype is available (1.22)
> 
> ```
> mvn archetype:generate -B -DarchetypeGroupId=io.jenkins.archetypes -DarchetypeArtifactId=empty-plugin -DhostOnJenkinsGitHub=true -DarchetypeVersion=1.22 -DartifactId=somefeature
> ```

is my fail. is maven 3.5.0
```sh
$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T03:39:06+08:00)
```
i will try to upgrade it.

**Comment by markixy** [comment]
**context**
maven 3.9.6 (use new empty repository, and no custom settings.xml)

**steps**
`$ mvn --version`
```sh
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: E:\Dev\apache-maven-3.9.6
Java version: 1.8.0_341, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_341\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
`$ mvn archetype:generate -B -DarchetypeGroupId=io.jenkins.archetypes -DarchetypeArtifactId=empty-plugin -DhostOnJenkinsGitHub=true -DarchetypeVersion=1.22 -DartifactId=somefeature`
`$ cd somefeature`
`$ mvn verify`
```sh
[INFO] Scanning for projects...
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/plugin/4.75/plugin-4.75.pom
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/plugin/4.75/plugin-4.75.pom (54 kB at 18 kB/s)
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/org/jenkins-ci/tools/maven-hpi-plugin/3.50/maven-hpi-plugin-3.50.pom
...
Downloaded from central: https://repo.maven.apache.org/maven2/org/mockito/mockito-bom/5.6.0/mockito-bom-5.6.0.pom (3.0 kB at 16 kB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ io.jenkins.plugins:somefeature:${revision}${changelist}, E:\WorkSpace\ideaIC\test\somefeature\pom.xml, line 13, column 14
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.jenkins.plugins:somefeature:1.0-SNAPSHOT (E:\WorkSpace\ideaIC\test\somefeature\pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ io.jenkins.plugins:somefeature:${revision}${changelist}, E:\WorkSpace\ideaIC\test\somefeature\pom.xml, line 13, column 14
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

whole log in 
[running.log](https://github.com/jenkinsci/archetypes/files/13804612/running.log)

What did I do wrong? @jonesbusy @NotMyFault

**Comment by MarkEWaite** [comment]
> What did I do wrong?

Thanks for including the full log file.  That made the diagnosis much easier than trying to guess what happened.  In that log file, there is a line:

> Java version: 1.8.0_341, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_341\jre

The Jenkins project stopped supporting Java 8 over a year ago.  We'll stop supporting Java 11 in Oct 2024.  You can install either Java 17 or Java 21 and use it to develop plugins that run on Java 11, Java 17, and Java 21.  You can also install Java 11 to develop plugins that run on Java 11, Java 17, and Java 21, but by the end of October 2024, the Jenkins project will stop supporting Java 11.

**Comment by markixy** [comment]
Oh, thanks.  But i must use Java 8 due to historical reasons, can i use previous version of archetype?

**Comment by MarkEWaite** [comment]
> Oh, thanks. But i must use Java 8 due to historical reasons, can i use previous version of archetype?

There were versions of the archetype that supported Java 8 and there are Jenkins versions that support Java 8, but the Jenkins developer community stopped supporting Java 8 long ago.  You're unlikely to receive much help from Jenkins developers to create a new plugin with Java 8.  I know that I'm not interested in doing that sort of exploration of history to try to find the combination of Java versions, Maven versions, Jenkins versions, and plugin versions that can create a new plugin with Java 8.

Please review the historical reasons with the people that gave you those historical reasons and persuade them that Java 8 is the wrong choice as the JDK for Jenkins plugin development.

**Comment by markixy** [comment]
archetype 1.22 + Java 17 work well.
archetype 1.7 + Java 8 work well.

No continue attempts.
